import pytest
import pandas as pd
import numpy as np
import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.streamlit_app import process_features


@pytest.fixture
def mock_preprocessor():
    """Provides a dummy preprocessor structure generated by the training pipeline."""
    return {
        "features": ["grid", "driver_age", "driverRef_encoded"],
        "imputation_medians": {
            "grid": 10.0,
            "driver_age": 28.5
        },
        "encoders": {
            "driverRef": {
                "map": {"verstappen": 0.8, "hamilton": 0.7},
                "global_mean": 0.5
            }
        }
    }


def test_process_features_target_encoding(mock_preprocessor):
    """Ensure categoricals are correctly mapped and filled with global mean if unknown."""
    df_in = pd.DataFrame({
        "grid": [1, 2, 3],
        "driver_age": [25, 38, 22],
        "driverRef": ["verstappen", "hamilton", "unknown_driver"]
    })
    
    df_out = process_features(df_in, mock_preprocessor)
    
    assert "driverRef_encoded" in df_out.columns
    assert "driverRef" not in df_out.columns
    
    # Check known drivers
    assert df_out.loc[0, "driverRef_encoded"] == 0.8
    assert df_out.loc[1, "driverRef_encoded"] == 0.7
    # Check unknown driver fallback
    assert df_out.loc[2, "driverRef_encoded"] == 0.5


def test_process_features_missing_columns(mock_preprocessor):
    """Ensure missing columns expected by the model are imputed using training medians."""
    # Input is missing "driver_age" entirely
    df_in = pd.DataFrame({
        "grid": [1],
        "driverRef": ["verstappen"]
    })
    
    df_out = process_features(df_in, mock_preprocessor)
    
    assert "driver_age" in df_out.columns
    assert df_out.loc[0, "driver_age"] == 28.5  # Taken from imputation_medians


def test_process_features_column_order(mock_preprocessor):
    """Ensure the output DataFrame perfectly matches the model's expected feature order."""
    df_in = pd.DataFrame({
        "driverRef": ["verstappen"],
        "driver_age": [25],
        "grid": [1]
    })
    
    df_out = process_features(df_in, mock_preprocessor)
    
    expected_order = mock_preprocessor["features"]
    assert list(df_out.columns) == expected_order
